# Generated by Django 3.2.5 on 2021-10-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('in_progress', 'in_progress'), ('is_ready', 'is_ready'), ('delivered', 'delivered')], default='new', max_length=100, verbose_name='status_order'),
        ),
    ]
