# Generated by Django 3.2.5 on 2021-10-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedproduct',
            name='prod_num',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
