# Generated by Django 3.2.5 on 2021-10-06 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_orderedproduct_prod_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedproduct',
            name='prod_num',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
