# Generated by Django 3.2.5 on 2021-10-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='all_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
