# Generated by Django 3.2.5 on 2023-04-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_order_all_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('in_progress', 'in_progress'), ('delivered', 'delivered')], default='new', max_length=100, verbose_name='status_order'),
        ),
    ]
